name: CI-environment-variables
# This tests whether environment variables are loaded correctly within the
# Docker container. The example sets the COMPOSER_PROCESS_TIMEOUT variable
# (which has a default of 300), and changes the command to "config" with args
# "process-timeout", which will show the value of the associated config setting.defaults:
# If the environment variables are loaded, the script should output 1. If they
# are ignored, it should output 300.

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        uses: php-actions/composer@v5
        with:
          php_version: 8.0
          ssh_key: ${{ secrets.SSH_KEY }}
          ssh_key_pub: ${{ secrets.SSH_KEY_PUB }}
          command: config
          args: process-timeout
        env:
          COMPOSER_PROCESS_TIMEOUT: 1
