name: Dump-Autoloader

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Dump autoload
        uses: php-actions/composer@v5
        with:
          command: dump-autoload
          only_args: --no-dev --no-interaction --classmap-authoritative
